### ISSUE TITLE
Install failes.

### ISSUE THREAD

**Issue by luckydonald** [yceruto/django-ajax#25]
Maybe some unprintable character/encoding? 
Maybe the readme file encoding?
 PyCharm is very picky with that.
```python
Collecting djangoajax
  Using cached djangoajax-2.3.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/zh/ntn59b4954l6tldmt4hn8bgc0000gn/T/pycharm-packaging2.tmp/djangoajax/setup.py", line 17, in <module>
        README = open(os.path.join(os.path.dirname(__file__), 'README.rst')).read()
      File "/Users/luckydonald/Documents/Programmieren/Python/my-project.git/virtualenv_3.4.3_brew.venv/bin/../lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 4394: ordinal not in range(128)
    
    ----------------------------------------

Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/zh/ntn59b4954l6tldmt4hn8bgc0000gn/T/pycharm-packaging2.tmp/djangoajax
```
Mac OS X 10.9.5, PyCharm 4.5, Python 3.4.3 (via brew) inside a virtualenv.

![bildschirmfoto 2015-09-27 um 01 11 05](https://cloud.githubusercontent.com/assets/2737108/10120306/ffeef7d2-64b4-11e5-86d2-0cb0dde81f94.png)

**Comment by luckydonald** [comment]
Some solutions already encountered:
 - https://github.com/ZeevG/python-forecast.io/issues/27#issuecomment-77377042
 - https://github.com/carpedm20/emoji/issues/5
