### ISSUE TITLE
1 positional argument but 2 positional arguments 

### ISSUE THREAD

**Issue by felixyin** [yceruto/django-ajax#46]
error is:
TypeError: dumps() takes 1 positional argument but 2 positional arguments (and 2 keyword-only arguments) were given:

code is:
```python
@ajax
def create_comment(request, pk):
    bcf = BlogCommentForm(request.POST)
    if bcf.is_valid():
        desc = request.POST['description']
        # if desc and len(str(desc)) < 5:
        # raise ValidationError('输入长度不能小于5')
        bc = BlogComment.objects.create(description=desc, author=request.user, blog=(get_object_or_404(Blog, pk=pk)))
        return {'id': bc.id, 'description': bc.description, 'author': bc.author, 'blog': bc.blog,
                'post_date': datetime.datetime.today()}
    else:
        e = bcf.errors['description']
        # print(e)
        # raise ValidationError(_("error..."))
        x = 1 / 0
```

```javascript
$(function () {

            $("#form_comment_create").on('submit', function (e) {
                e.preventDefault();

                var form = $(this).ajaxSubmit();
                var xhr = form.data('jqxhr');
                xhr.done(function (result, status) {
                    if (status === 'success') {
                        var comment = result.content;
                        $('#div-comment-area').before('<hr>\n        <p>'
                            + comment.author + '('
                            + comment.post_date + ') - > '
                            + comment.description + '</p>')
                    }
                });
                xhr.fail(function (result, status) {
                    console.log(result)
                    alert(result.content)
                });
            });

        });
```

**Comment by yceruto** [comment]
Hi @felixyin, thanks for reporting this issue, but to understand what happens I need at least the full trace stack of the error. Could you provide it? Cheers!

**Comment by yceruto** [comment]
Also django and python version?

**Comment by brendanwood** [comment]
Hello, I have encountered an issue that appears to be similar. It comes up when hitting an unhandled exception:
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bwood/.virtualenvs/passiv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/bwood/.virtualenvs/passiv/lib/python3.7/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/bwood/.virtualenvs/passiv/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/bwood/.virtualenvs/passiv/lib/python3.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/bwood/.virtualenvs/passiv/lib/python3.7/site-packages/django_ajax/decorators.py", line 70, in inner
    return render_to_json(exception, {'request': request})
  File "/home/bwood/.virtualenvs/passiv/lib/python3.7/site-packages/django_ajax/shortcuts.py", line 109, in render_to_json
    return JSONResponse(data,  *args, **kwargs)
  File "/home/bwood/.virtualenvs/passiv/lib/python3.7/site-packages/django_ajax/response.py", line 29, in __init__
    content=serialize_to_json(data, *args, **kwargs),
  File "/home/bwood/.virtualenvs/passiv/lib/python3.7/site-packages/django_ajax/encoder.py", line 68, in serialize_to_json
    return json.dumps(data, *args, **kwargs)
TypeError: dumps() takes 1 positional argument but 2 positional arguments (and 2 keyword-only arguments) were given
```

I put a breakpoint in the `serialize_to_json` function, here are the arguments for it:

```
data = {'status': 500, 'statusText': 'INTERNAL SERVER ERROR', 'content': <HttpResponseServerError status_code=500, "text/plain">}
args = ({'request': <WSGIRequest: GET '/ajax/accounts/271f6127-c752-4f3d-8d6e-f578dd43d382'>},)
kwargs = {'sort_keys': True, 'cls': <class 'django_ajax.encoder.LazyJSONEncoder'>}
```

Versions:
```
Python 3.7.0
Django==2.0.8
djangoajax==3.0.2
```

**Comment by brendanwood** [comment]
It looks like Python changed the behaviour of `json.dumps` in version 3.6, so it can only have one positional argument.

**Comment by brendanwood** [comment]
Context for the change: https://bugs.python.org/issue18726

**Comment by yceruto** [comment]
@brendanwood thanks for providing the details, I'll check out soon.

**Comment by yceruto** [comment]
@brendanwood could you confirm that this change https://github.com/yceruto/django-ajax/pull/47/files#diff-0c8679fdacb607b809bebc1d1ca46705R70 fix the problem?

**Comment by brendanwood** [comment]
Thanks, that fixed it as far as I can tell. Much appreciated!

**Comment by wuyinong** [comment]
thanks
