### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'request'

### ISSUE THREAD

**Issue by TvoroG** [yceruto/django-ajax#50]
Hi!

Example:
```python
from django.http import Http404
from django_ajax.decorators import ajax

@ajax
def some_page(request):
    raise Http404
```

Traceback:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django_ajax/decorators.py", line 70, in inner
    return render_to_json(exception, **{'request': request})
  File "/usr/local/lib/python3.6/site-packages/django_ajax/shortcuts.py", line 109, in render_to_json
    return JSONResponse(data,  *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django_ajax/response.py", line 29, in __init__
    content=serialize_to_json(data, *args, **kwargs),
  File "/usr/local/lib/python3.6/site-packages/django_ajax/encoder.py", line 68, in serialize_to_json
    return json.dumps(data, *args, **kwargs)
  File "/usr/local/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
TypeError: __init__() got an unexpected keyword argument 'request'
```

djangoajax==3.0.3

**Comment by yceruto** [comment]
Hi @TvoroG, What is the Django version you are using with djangoajax==3.0.3?

**Comment by TvoroG** [comment]
django==2.1.5

**Comment by yceruto** [comment]
Mmm, that's weird, I tested that case:
https://github.com/yceruto/django-ajax/blob/50eb1304db1b93d10d0a60da9910110f8c3d2bae/tests/example/views.py#L40-L42
and the last Travis Job with Python3.6 + Django==2.1.5 + djangoajax==3.0.3 given me a green :/
https://travis-ci.org/yceruto/django-ajax/jobs/490053617

**Comment by yceruto** [comment]
Mmm, sorry, that's the middleware in action, I'll try with the decorator directly.

**Comment by yceruto** [comment]
Fixed in https://github.com/yceruto/django-ajax/pull/51, I'm going to release a new version as soon as possible, thanks for reporting the error.

**Comment by yceruto** [comment]
Done in https://github.com/yceruto/django-ajax/releases/tag/3.1.0

**Comment by TvoroG** [comment]
Thanks a lot for the quick fix, @yceruto!
